### PR TITLE
Qt/EclipseGenerators: clean and buildCfg argument

### PR DESCRIPTION
**Pull request by rhubert**
With --clean the generator removes the destination directory before generating
the project files. This may be usefull in case of a non working project because of
changes in the creator.user file.

The --buildCfg argument can be used to add additional buildConfigs. For example
--buildCfg "Bob dev DEBUG"::"-b -DDEBUG=1".

### CODE REVIEW

**Comment by jkloetzke** [comment]
Hmm, --clean is already used for another purpose in "bob build/dev". That may even be worth passing it through bob project. Maybe "--overwrite" is a better name?

**Comment by rhubert** [comment]
yep

**Comment by jkloetzke** [comment]
Ok. Did it get some light testing and is it ready for merge?

**Comment by rhubert** [comment]
Tested both on a larger project today. Its ready to merge.

**Pull request merged**
