### PR TITLE
Add support for cloning a subset of submodules

### PR DESCRIPTION
**Pull request by jkloetzke**
Instead of cloning all submodules it is possible to give a list of paths
to the "submodules" property. Only these submodules will be cloned and
all others will be left uninitialized. This is not possible for
sub-submodules.

@rhubert Is this sufficient for your use case?

### CODE REVIEW

**Comment by rhubert** [comment]
Thanks! Worked for my use-case :+1: 

`bob status` shows `unpushed local commits` for submodules?

with

```yaml
 root : True
 checkoutSCM:
  -
    scm: git
    url: https://git.codelabs.ch/muen.git
    branch: devel
    submodules:
        - tools/mugenschedcfg
        - tools/sbs

 buildScript: "true"
 packageScript: "true"
```

```
   STATUS u    dev/src/muen/1/workspace/.
   > submodule './tools/mugenschedcfg' unpushed local commits:
      fa04009 (grafted, HEAD) Minor improvements to plan plotting
   > submodule './tools/sbs' unpushed local commits:
      eebbc8f (grafted, HEAD) Extend sbs_inspect tool and provide stream verifier
```

**Comment by jkloetzke** [comment]
> Thanks! Worked for my use-case +1

Cool.

> `bob status` shows `unpushed local commits` for submodules?

Not so cool. :wink: I'll look into it. This is certainly wrong.

**Comment by jkloetzke** [comment]
> > `bob status` shows `unpushed local commits` for submodules?
> 
> Not so cool. wink I'll look into it. This is certainly wrong.

This is an artefact of the shallow and single-branch cloning. At least the `tools/mugenschedcfg` submodule checks out a commit from the "devel" branch while the default branch of the submodule is "master". Setting `shallowSubmodules: False` will "fix" the problem but it will clone much more.

In principle this problem can happen for regular checkouts with `shallow: 1` too when using `commit: ...`.

Not sure what is the best approach here. Suppress the unpushed commits check on shallow clones? Or keep it and amend the manpage?

**Comment by rhubert** [comment]
I'd keep it and make a note in the manpage.

**Pull request merged**
