### PR TITLE
Use internal extractors on win32

### PR DESCRIPTION
**Pull request by jkloetzke**
Turns out that at least tarfile is not usable on POSIX systems for us due to the `chmod` handling. Play safe and use it only on native Windows where this doesn't make a difference. Given that, we can also prefer the Python versions there.

### CODE REVIEW

**Comment by jkloetzke** [comment]
@sbixl Could you give this a try?

**Comment by sbixl** [comment]
Sorry for the delay. I will test it next week and give you feedback soon.

**Comment by sbixl** [comment]
Did some testing today and it works like expected. Thanks for that improvement!

**Comment by jkloetzke** [comment]
Thanks for testing!

**Pull request merged**
