### PR TITLE
Parallel builds

### PR DESCRIPTION
**Pull request by jkloetzke**
Add the '-j' option to build packages in parallel.

### CODE REVIEW

**Comment by Kalabaza** [comment]
I think the generators (for qt and eclipse) must also be modified to have at least an extra configuration with the -j flag.

Also, I tried adding the flag to one of the tests (rerun-failed-build since it has some code and it is actually being compiled), but after deleting the semi-colon from the printf of the foo.c file the compilation error is not seen on the IDE, maybe the new text interfieres with the parsing of the log:

```
[Start    1] NOTE: CHECKOUT  root - dev/src/root/1/workspace 
[End      1] NOTE: CHECKOUT  root - dev/src/root/1/workspace 
[Start    2] NOTE: BUILD     root - dev/build/root/1/workspace
[End      2] ERR : BUILD     root - dev/build/root/1/workspace
[...      2] NOTE: |root| /home/user/BobBuildTool/test/rerun-failed-build/dev/src/root/1/workspace/foo.c: In function 'main':
[...      2] NOTE: |root| /home/user/BobBuildTool/test/rerun-failed-build/dev/src/root/1/workspace/foo.c:6:2: error: expected ';' before 'return'
[...      2] NOTE: |root|   return 0;
[...      2] NOTE: |root|   ^~~~~~
[...      2] NOTE: |root| Step failed with return status 1; Command: gcc -o foo $1/foo.c
[...      2] NOTE: |root| Call stack (most recent call first)
[...      2] NOTE: |root|     #0: Recipe root, line 2, in main
```

**Comment by jkloetzke** [comment]
Tested with QtCreator. LGTM...

**Comment by Kalabaza** [comment]
Thanks, now the errors are parsed correctly again.

**Comment by rhubert** [comment]
making bob with python 3.4 fails.

```
BobBuildTool$ make
Listing 'pym'...
Listing 'pym/bob'...
Compiling 'pym/bob/__init__.py'...
Compiling 'pym/bob/archive.py'...
***   File "pym/bob/archive.py", line 84
    async def uploadPackage(self, step, buildId, audit, content):
            ^
SyntaxError: invalid syntax
```

Checking for python >= 3.5 should also be done in the Makefile...

**Comment by jkloetzke** [comment]
Added a check that hopefully should trigger early enough.

**Comment by kkendzia** [comment]
Building with "bob dev -j4 <pkg>"
When the CheckoutStep (checkoutscript in this case) fails I run into an endless loop.
There is python script generating files which failed with a "FileNotFoundError" leading to a stuck buildId calculation.

**Comment by jkloetzke** [comment]
Hopefully fixed with the last commit... :)

**Comment by kkendzia** [comment]
Thanks! I deployed it on our test server and give a feedback in some days

**Comment by kkendzia** [comment]
Thanks! I deployed it on our test server and give a feedback in some days

**Comment by kkendzia** [comment]
Thanks! I deployed it on our test server and give a feedback in some days

**Comment by kkendzia** [comment]
Now the buildId (downloading liveid) calculation stucks even without a failing step.

**Comment by kkendzia** [comment]
Works fine for 1 week. Didn't have any problems and runs well

**Comment by jkloetzke** [comment]
Thanks for testing and the numerous feedback. :+1:

**Pull request merged**
