### PR TITLE
BOB_VERSION: add git infos

### PR DESCRIPTION
**Pull request by rhubert**
Append the output of git describe to BOB_VERSION.

### CODE REVIEW

**Comment by jkloetzke** [comment]
I've amended your commit and added proper support for installed copies and downloaded tarballs: https://github.com/jkloetzke/bob/commit/5550adfef1adf3c971ae5b2ab133aed7b6c80f7f Are you ok with that? I would still keep you as the author.

**Comment by rhubert** [comment]
Looks good to me. :+1: I don't mind if you remove me as author. What counts is the feature. ( and nobody can blame me for that ;) )

Btw. is `bobMinimumVersion` working for additional commits? Something like 
```yaml
bobMinimumVersion: "0.8-4"
```

**Comment by jkloetzke** [comment]
The version comparison function will ignore anything after the first dash (-). That is not according to semver but that is the output of git describe neither. It should be enough for our purposes, though. I've considered the correct implementation that would give something like "0.9-dev+v0.8.0-5-g5550adf" but that looks just plain ugly.

**Comment by jkloetzke** [comment]
To be more explicit: you cannot compare to a pre-relase version at all. For `bobMinimumVersion` you can only give one to three numbers separated by dots. Anything else will fail schema validation. That could be extended in the future, though.

**Comment by rhubert** [comment]
Understand. Shall I close this and you merge this from your branch?

**Comment by jkloetzke** [comment]
Yes, please. I've just pushed my rework.

**Pull request closed without merging**
