### PR TITLE
build: add bundle build

### PR DESCRIPTION
**Pull request by rhubert**
A bob-bundle collects all scm's neccessary to build a package in a tar-file. Next to the tar-file a scmOverrides file is generated to be able to rebuild the package only with the bundle.

Such a bundle can be used to build on a air-gapped system or to archive all sources of a build.

ATM only bundling of git and url-scm's is supported.

### CODE REVIEW

**Comment by rhubert** [comment]
TODO / RFC:

- [ ] black-box test
- [ ] add recipes to bundle?
- [ ] add some kind of unbundle command / script / ... ??

**Comment by jkloetzke** [comment]
Why closed? I did not look into the details but it at the first glance it sounded like a desirable feature...

**Comment by rhubert** [comment]
Just to not waste your time. :) 

I was caught up by reality shortly after pushing this. The initial idea to bundle only the `checkoutScm`s while still running the `checkoutScript`s doesn't work for all `checkoutScript` doing more fetches. (`cargo`, `alire`, `pip`, `meson subprojects download` ... ).  OTOH there are `checkoutScript`s that might be still needed on the `unbundled` machine (`autoreconf`, ...) so this is (as usual) much more complex...

I'm working on an update and will reopen this once I think it might hold a little longer...

**Comment by jkloetzke** [comment]
Thanks. :)

I think the only reasonable option is to pack the whole source workspace after the checkout step is finished. Very much like the binary artifacts are treated now for package steps. Of course, this will only work for deterministic checkout steps...

**Pull request closed without merging**
