### PR TITLE
Add "show" command

### PR DESCRIPTION
**Pull request by jkloetzke**
The show command can be used to show all properties of a package as
they were computed by Bob when evaluating the recipes. The output can
be filtered and formatted in various ways. There is a special 'diff'
output format that produces a diff view of two packages.

- [x] Add documentation
- [x] Tests

### CODE REVIEW

**Comment by jkloetzke** [comment]
I think this is basically finished. If there are no objections or suggestions I would merge it...

**Comment by rhubert** [comment]
:+1: I'm missing the recipe / packageName in the output?

**Comment by jkloetzke** [comment]
Good point. I'll add it to the ``meta`` section...

**Comment by rhubert** [comment]
:+1: looks good now. Only the `#0` appended to the `recipe` property of `checkoutSCM` is somehow strange / unexpected at first glace..

**Comment by jkloetzke** [comment]
> Only the `#0` appended to the `recipe` property of `checkoutSCM` is somehow strange / unexpected at first glace..

That was one of the not so good ideas back at the beginning. It was introduced in ef840103a for `query-scm` to let scripts know where the SCM came from. It should have been called `origin` or something and the `#<num>` is pointless in the face of `multiPackage`. I guess we could remove it...

**Comment by Ferruck** [comment]
Looks generally good, the only thing I'm missing is some kind of heading if you're querying multiple packages at once, e.g. by using the bobpaths syntax.

**Comment by jkloetzke** [comment]
Good point. I think we could add a comment in the yaml and flat outputs. But json does not allow comments...

```yaml
---
# buildall/utils::e2fsprogs
buildTools:
    make: buildall/devel::make
    pkg-config: buildall/devel::pkg-config
    target-toolchain: buildall/devel::host-compat-toolchain
buildToolsWeak:
    make: buildall/devel::make
    pkg-config: buildall/devel::pkg-config
...
```

```
# buildall/utils::e2fsprogs
[19].buildTools.make=buildall/devel::make
[19].buildTools.pkg-config=buildall/devel::pkg-config
[19].buildTools.target-toolchain=buildall/devel::host-compat-toolchain
[19].buildToolsWeak.make=buildall/devel::make
[19].buildToolsWeak.pkg-config=buildall/devel::pkg-config
```

**Comment by Ferruck** [comment]
Then maybe adding another property would be the more consistent variant? Something like `packagePath`?!

**Comment by rhubert** [comment]
Not sure if anybody needs json / yaml output on stdout? Maybe it's a option to write them to a file where the filename matches the recipe name?

**Comment by Ferruck** [comment]
Well, piping the output to something else is a valid use case, IMHO...

**Comment by jkloetzke** [comment]
> Then maybe adding another property would be the more consistent variant? Something like `packagePath`?!

This is already there: `meta.package`. It's just no at the top because of the sorting...

> Not sure if anybody needs json / yaml output on stdout? Maybe it's a option to write them to a file where the filename matches the recipe name?

The output was intentionally thought to be parseable by other scripts. Therefore also the json and flat formats. And the yaml output naturally looks like the recipes so it was a good match too..

**Comment by Ferruck** [comment]
Sorry, I missed `meta.package`. This is enough, at least for me. LGTM

**Pull request merged**
