### PR TITLE
bob project: add eclipseProjectGenerator

### PR DESCRIPTION
**Pull request by rhubert**
This adds Eclipse CDT support to Bob. All dependencies are added as virtual folders
pointing to the src-directory of the package. For all x86 executables launch configs
will be generated.

What do you think? Shall this also be a build-in generator?

### CODE REVIEW

**Comment by jkloetzke** [comment]
Do you have anything to add or can I merge?

**Comment by rhubert** [comment]
Not sure. During testing I hit https://bugs.eclipse.org/bugs/show_bug.cgi?id=400073 (boost)
As a workaround it is be possible to exclude linked folders from build. They won't get indexed in this case but you can work with the rest. 

It the moment you have to be quicker than the indexer to exclude big folders. I'm thinking of a --exclude=<package> argument for eclipseGenerator. What's you opinion?

**Comment by jkloetzke** [comment]
The "--exclude" options sounds like a viable workaround. Maybe let it take package names (with globbing)?

**Comment by rhubert** [comment]
--exclude added. You can use regex, e.g. --exclude .*boost.* . Now it's ready to merge from my side.

**Comment by jkloetzke** [comment]
:+1:

**Pull request merged**
