### PR TITLE
Fix detection of closing single quotation mark in StringParser

### PR DESCRIPTION
**Pull request by gruberchr**
There is a bug in function `getSingleQuoted()` of class `StringParser`, which ignores a closing single quotation mark, if it is at the end of the string. This bug is fixed.

### CODE REVIEW

**Comment by gruberchr** [comment]
By the way, there is no test case at the moment, which checks, if variable and command substitution is disabled in substrings quoted with single quotes.

**Comment by jkloetzke** [comment]
Good catch. I took the freedom to reorder the commits so that a `git bisect` will not trip on the test case without the fix. I also adjusted the commit messages slightly.

> By the way, there is no test case at the moment, which checks, if variable and command substitution is disabled in substrings quoted with single quotes.

You're right. Do you plan to add some test cases? I could also put them on my todo list, though...

**Comment by gruberchr** [comment]
> You're right. Do you plan to add some test cases? I could also put them on my todo list, though...

No, we don't. Put it on your todo list.

**Comment by jkloetzke** [comment]
> > You're right. Do you plan to add some test cases? I could also put them on my todo list, though...
> 
> No, we don't. Put it on your todo list.

Ok, no problem.

**Pull request merged**
