### PR TITLE
Multi multi package

### PR DESCRIPTION
**Pull request by rhubert**
fixes #90 even if it's not a bug..

during testing our new college also found a bug when installing bob from a detached head git... :disappointed:

### CODE REVIEW

**Comment by Ferruck** [comment]
I probably found another bug. Let's say you've something like this:

```yaml
…preamble…

buildVars: [YOUR_VAR]
buildScript:
   if [[ ${YOUR_VAR} -eq "1" ]]; then
      LOCALVAR="foo"
   else
      LOCALVAR="bar"
   fi

…

multiPackage:
   foo:
      environment:
         YOUR_VAR: "1"
      multiPackage:
…
   bar:
      environment:
         YOUR_VAR: "0"
      multiPackage:
…
```

This works as expected. But if you change, let's say, `foo` to `''`, e.g.

```yaml
…
multiPackage:
   '':
      environement:
…
```

you get a `YOUR_VAR: unbound variable`.

Is this a bug or am I just holding it wrong?

**Comment by rhubert** [comment]
This is a bug with the new nameless multi package... 

Am 22. Dezember 2016 08:55:20 MEZ, schrieb Philipp Trommler <notifications@github.com>:
>I probably found another bug. Let's say you've something like this:
>
>```yaml
>…preamble…
>
>buildVars: [YOUR_VAR]
>buildScript:
>   if [[ ${YOUR_VAR} -eq "1" ]]; then
>      LOCALVAR="foo"
>   else
>      LOCALVAR="bar"
>   fi
>
>…
>
>multiPackage:
>   foo:
>      environment:
>         YOUR_VAR: "1"
>      multiPackage:
>…
>   bar:
>      environment:
>         YOUR_VAR: "0"
>      multiPackage:
>…
>```
>
>This works as expected. But if you change, let's say, `foo` to `''`,
>e.g.
>
>```yaml
>…
>multiPackage:
>   '':
>      environement:
>…
>```
>
>you get a `YOUR_VAR: unbound variable`.
>
>Is this a bug or am I just holding it wrong?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/BobBuildTool/bob/pull/92#issuecomment-268740473

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by rhubert** [comment]
This only happens if you have a multipackage below a namelass multipackage right? Setting a environment variable in a nameless multi package without a nested one should work? 
Nevertheless I see a usecase for your example. I'll have a deeper look at this in the afternoon - unless you already fixed it. :)

Am 22. Dezember 2016 08:55:20 MEZ, schrieb Philipp Trommler <notifications@github.com>:
>I probably found another bug. Let's say you've something like this:
>
>```yaml
>…preamble…
>
>buildVars: [YOUR_VAR]
>buildScript:
>   if [[ ${YOUR_VAR} -eq "1" ]]; then
>      LOCALVAR="foo"
>   else
>      LOCALVAR="bar"
>   fi
>
>…
>
>multiPackage:
>   foo:
>      environment:
>         YOUR_VAR: "1"
>      multiPackage:
>…
>   bar:
>      environment:
>         YOUR_VAR: "0"
>      multiPackage:
>…
>```
>
>This works as expected. But if you change, let's say, `foo` to `''`,
>e.g.
>
>```yaml
>…
>multiPackage:
>   '':
>      environement:
>…
>```
>
>you get a `YOUR_VAR: unbound variable`.
>
>Is this a bug or am I just holding it wrong?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/BobBuildTool/bob/pull/92#issuecomment-268740473

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by Ferruck** [comment]
I'd have to test it without the nested `multiPackage` inside the nameless one. I'll try to fix it if you could give me a hint where to start... :wink:

**Comment by rhubert** [comment]
I pushed another commit which should fix your issue. The obvious problem was that there are two classes with the same name. The base class of the nameless package was already added and the base class of the named multiPackage which has the unnamed base was skipped.

Keep in mind to remove the cache file...

**Comment by rhubert** [comment]
... this is still broken... and I have a knot in my head...  :angry:

**Comment by rhubert** [comment]
I think the root cause of all my trouble was a unsorted processing of the packages. For nested multiPackages they must be resolved in ascending oder ( from base to special ). 
@Ferruck can u test this one more time? :wink:

**Comment by Ferruck** [comment]
I started testing right now. One thing I already noticed: Your fix for the `git`-based versioning is not complete. At the moment it breaks the `install` command. Easy fix for this, replace

```
git describe --tags --dirty > $(DESTDIR)/lib/bob/version ; \
```

with

```
git describe --tags --dirty > $(DESTDIR)/lib/bob/version && ([[ $$? -ne 0 ]] && rm -rf $(DESTDIR)/lib/bob/version) || : ; \
```

Further test results in a moment.

**Comment by Ferruck** [comment]
Looks good, found no errors. Thanks!

**Comment by rhubert** [comment]
Can you open a separate pr for this? I'll remove my commit... Thanks

Am 23. Dezember 2016 09:20:09 MEZ, schrieb Philipp Trommler <notifications@github.com>:
>I started testing right now. One thing I already noticed: Your fix for
>the `git`-based versioning is not complete. At the moment it breaks the
>`install` command. Easy fix for this, replace
>
>```
>git describe --tags --dirty > $(DESTDIR)/lib/bob/version ; \
>```
>
>with
>
>```
>git describe --tags --dirty > $(DESTDIR)/lib/bob/version && ([[ $$? -ne
>0 ]] && rm -rf $(DESTDIR)/lib/bob/version) || : ; \
>```
>
>Further test results in a moment.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/BobBuildTool/bob/pull/92#issuecomment-268955271

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by Ferruck** [comment]
I'll do this.

**Comment by jkloetzke** [comment]
I've re-implemented the proposal with correct (anonymous) class resolving: https://github.com/jkloetzke/bob/tree/nested-multipackage This branch does not implement "unnamed" multipackages. For that feature the class resolving is still broken and will need further refactoring of `Recipe.resolveClasses`.

@Ferruck Can you test again with this branch?

**Pull request closed without merging**
